package com.capstone.chatapp.data.security

import android.content.Context
import android.content.SharedPreferences
import android.util.Base64
import androidx.security.crypto.EncryptedSharedPreferences
import androidx.security.crypto.MasterKey
import com.capstone.chatapp.data.model.Message
import com.google.crypto.tink.subtle.AesGcmJce
import com.google.crypto.tink.subtle.Hkdf
import com.google.crypto.tink.subtle.X25519
import java.util.concurrent.ConcurrentHashMap

/**
 * Per-user X25519 identity + relay-blind AES-256-GCM encryption for targeted 1:1 traffic.
 *
 * Each user gets one long-term X25519 key pair, generated by Tink's audited [X25519]
 * implementation. The raw private key bytes are never written to disk in the clear: they live
 * only in [EncryptedSharedPreferences], whose wrapping AES key is a [MasterKey] resident in the
 * Android Keystore (hardware-backed where available, non-exportable either way). Android does
 * not support storing raw X25519 key material natively in the Keystore below API 31 (and support
 * is inconsistent even above it), so "envelope encryption" of the key blob by a Keystore-backed
 * AES key is the standard, portable way to honor "private key in the Keystore" down to minSdk 24.
 *
 * Encryption between two users derives a static AES-256 key with X25519 ECDH + HKDF-SHA256 from
 * (my private key, their public key). X25519 is a Diffie-Hellman function, so the peer derives
 * the *same* key from (their private key, my public key) — meaning either side can also decrypt
 * their own sent history later, not just what they receive, without a second ciphertext copy.
 * The derived key is cached per peer ([derivedKeyCache]) since it never changes while both public
 * keys stay the same. [AesGcmJce] then seals each message with AES-256-GCM, generating and
 * bundling its own random IV — so [com.capstone.chatapp.data.transport.Packet.nonce] stays unused
 * by design rather than duplicating IV bookkeeping the AEAD wrapper already does correctly.
 *
 * This is intentionally a static per-pair key (no ratcheting/forward secrecy) — the goal here is
 * relay blindness (Firestore and any BLE/Wi-Fi-Direct relay only ever see ciphertext), not a full
 * Signal-protocol session. See SESSION_CONTEXT.md for the threat model this does and doesn't cover.
 */
class CryptoManager(context: Context) {
    private val appContext = context.applicationContext

    private var boundUid: String? = null
    private var identity: Identity? = null
    private val derivedKeyCache = ConcurrentHashMap<String, ByteArray>()

    private data class Identity(val privateKey: ByteArray, val publicKey: ByteArray)

    /** Loads (or generates on first run) this user's identity key pair. Call after auth succeeds. */
    @Synchronized
    fun bind(uid: String) {
        if (boundUid == uid && identity != null) return
        boundUid = uid
        derivedKeyCache.clear()
        identity = loadOrCreateIdentity(uid)
    }

    /** Drops the in-memory identity + derived-key cache on logout. The on-disk keyset is untouched
     *  so signing back in as the same user restores the same identity (and the same safety number). */
    @Synchronized
    fun clear() {
        boundUid = null
        identity = null
        derivedKeyCache.clear()
    }

    val isBound: Boolean get() = identity != null

    fun publicKeyBase64(): String = Base64.encodeToString(requireIdentity().publicKey, Base64.NO_WRAP)

    fun encryptFor(peerId: String, peerPublicKeyBase64: String, plaintext: ByteArray): ByteArray {
        val aead = AesGcmJce(derivedKey(peerId, peerPublicKeyBase64))
        return aead.encrypt(plaintext, associatedData(peerId))
    }

    fun decryptFrom(peerId: String, peerPublicKeyBase64: String, ciphertext: ByteArray): ByteArray {
        val aead = AesGcmJce(derivedKey(peerId, peerPublicKeyBase64))
        return aead.decrypt(ciphertext, associatedData(peerId))
    }

    /** Binds ciphertext to this specific conversation so it can't be replayed into another chat. */
    private fun associatedData(peerId: String): ByteArray =
        Message.getChatId(requireUid(), peerId).toByteArray(Charsets.UTF_8)

    private fun derivedKey(peerId: String, peerPublicKeyBase64: String): ByteArray =
        derivedKeyCache.getOrPut(peerId) {
            val peerPublicKey = Base64.decode(peerPublicKeyBase64, Base64.NO_WRAP)
            val sharedSecret = X25519.computeSharedSecret(requireIdentity().privateKey, peerPublicKey)
            Hkdf.computeHkdf("HMACSHA256", sharedSecret, /* salt = */ null, HKDF_INFO, /* size = */ 32)
        }

    private fun requireUid(): String = checkNotNull(boundUid) { "CryptoManager.bind(uid) not called" }
    private fun requireIdentity(): Identity = checkNotNull(identity) { "CryptoManager.bind(uid) not called" }

    private fun loadOrCreateIdentity(uid: String): Identity {
        val prefs = encryptedPrefs(uid)
        val storedPrivate = prefs.getString(KEY_PRIVATE, null)
        val storedPublic = prefs.getString(KEY_PUBLIC, null)
        if (storedPrivate != null && storedPublic != null) {
            return Identity(
                Base64.decode(storedPrivate, Base64.NO_WRAP),
                Base64.decode(storedPublic, Base64.NO_WRAP),
            )
        }
        val privateKey = X25519.generatePrivateKey()
        val publicKey = X25519.publicFromPrivate(privateKey)
        prefs.edit()
            .putString(KEY_PRIVATE, Base64.encodeToString(privateKey, Base64.NO_WRAP))
            .putString(KEY_PUBLIC, Base64.encodeToString(publicKey, Base64.NO_WRAP))
            .apply()
        return Identity(privateKey, publicKey)
    }

    /** One [EncryptedSharedPreferences] file per uid, so multiple accounts on one device (or a
     *  logout/login as someone else) never mix identities. */
    private fun encryptedPrefs(uid: String): SharedPreferences {
        val masterKey = MasterKey.Builder(appContext, "${MASTER_KEY_ALIAS}_$uid")
            .setKeyScheme(MasterKey.KeyScheme.AES256_GCM)
            .build()
        return EncryptedSharedPreferences.create(
            appContext,
            "${PREFS_NAME}_$uid",
            masterKey,
            EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,
            EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM,
        )
    }

    companion object {
        private const val MASTER_KEY_ALIAS = "safesphere_identity_master_key"
        private const val PREFS_NAME = "safesphere_identity"
        private const val KEY_PRIVATE = "x25519_private"
        private const val KEY_PUBLIC = "x25519_public"
        private val HKDF_INFO = "SafeSphere-E2E-v1".toByteArray(Charsets.UTF_8)
    }
}
